### PR TITLE
Check if algorithm is the same of the system

### PR DESCRIPTION
**Pull request by nasverdes**
Here is my contribuition about the issue #16

### CODE REVIEW

**Comment by dvsekhvalnov** [comment]
Here is how Strict validation implemented in other library: https://github.com/dvsekhvalnov/jose-jwt#strict-validation

I'll also add some comments to code.

**Comment by EvertonSalesBranco** [comment]
In my code I forgot to put an example of Decode...
payload, headers, err := jose.Decode(token, publicKey, jose.RS256)

It's so close of [you reference](https://github.com/dvsekhvalnov/jose-jwt#strict-validation).

**Comment by EvertonSalesBranco** [comment]
Your suggestion is ok for me, but I haven't found any examples of that.

**Comment by dvsekhvalnov** [comment]
Feel to contribute docs and helper functions :)

**Comment by dvsekhvalnov** [comment]
Here is sketch for helper:

```go
EnsureSignAlg(expectedAlg string, interface{} key) func (h map[string]interface{}, p string) interface{} {            
    //generate func
    return func (h map[string]interface{}, p string) interface{} {
       if h['alg']!=expectedAlg {
          return errors.New("Expected different signing alg");
       } 
       //pass-through key
       return key; 
    }
}
```

**Comment by dvsekhvalnov** [comment]
Hi @nasverdes , if you still around, is this pull still relevant?

**Comment by dvsekhvalnov** [comment]
Closed due to inactivity.

**Pull request closed without merging**
